### PR TITLE
Monorepo Tooling

### LINKED ISSUE #20: Project-level CI+tooling (i.e. linting)

### PR DESCRIPTION
**Pull request by cha0sg0d**
Creates the basis for simple monorepo tooling.
Closes #20 
- [x] Eslint
- [x] Prettier
- [x] Run prettier + eslint on each commit
- [x] Enforce [conventional commit](https://github.com/conventional-changelog/commitlint) messages
- [x] Github Action to Lint + Format on each push (and tests once we have them)
- [x] Recommended VS Code settings   
- [x] Switches to [npm workspaces](https://ruanmartinelli.com/posts/npm-7-workspaces-1) and removes Lerna. Rationale: Most people only use yarn for workspaces, but now npm has them and we don't need to install yarn.
- [x] Adds an MIT License for Personae Labs, LLC 

Some helpful tips + notes:

1. To run a command, such as test, run `npm run test`. 
2. Make sure your commits follow the conventional commit [spec](https://www.conventionalcommits.org/en/v1.0.0/#examples)
3. Hit me up if anything isn't working! Each workspace can define its own eslint rules, prettier formatting, workspace commands, etc, so this tooling is very lightweight and unopinionated.

### CODE REVIEW

**Comment by lsankar4033** [comment]
lgtm!

@DanTehrani any comments? i.e. on npm workspaces or licenses?

**Comment by DanTehrani** [comment]
Nice setup!
I advocate for MIT as well!  But just wanna make sure that there aren’t dependencies under a copyleft license like GPL. (afaik there aren’t any)

Personally yarn > npm because yarn is a lot faster. wdyt? cc. @lsankar4033  @amirgamil  (I use yarn for dep management in basically all of my projects)
> Switches to [npm workspaces](https://ruanmartinelli.com/posts/npm-7-workspaces-1)



Following conventional commits sounds good!

**Comment by cha0sg0d** [comment]
> Personally yarn > npm because yarn is a lot faster. wdyt? cc. @lsankar4033 @amirgamil (I use yarn for dep management in basically all of my projects)

Re performance, I just read this https://blog.logrocket.com/javascript-package-managers-compared/. First of all seems like yarn, npm, pnpm all have basic feature parity. Second of all, if performance is a concern we could use `pnpm`. Works out of the box with npm and has a different installation model (content addressable storage) that is more performant.

**Comment by DanTehrani** [comment]
@cha0sg0d 
pnpm looks good to me! Thanks for checking out the comparison! 

So I think we can go with an npm-compatible solution, which is either npm or pnpm (so committing package-lock.json instead of yarn.lock).
The merkle-tree backend and the API currently use yarn so I will switch them to pnpm after this PR is merged.

**Comment by cha0sg0d** [comment]
@lsankar4033 @DanTehrani I switched to pnpm. CI is ~20 sec faster and install is quick as well. We'll have to migrate anything using yarn or npm in the `packages` folder once this is merged, and I'm happy to do that.

**Pull request merged**
