### PR TITLE
Add depth count to `Post`

### PR DESCRIPTION
**Pull request by DanTehrani**
Add column `depth` to `Post`.

On staging, I deleted all `Post` records (and `Upvote` due to foreign key relation) and ran the migration, adding the `depth` column. Also re-populated the staging db with test data.

### CODE REVIEW

**Comment by DanTehrani** [comment]
Ok the proof generation is failing again on this branch. Investigating.

**Comment by cha0sg0d** [comment]
> Ok the proof generation is failing again on this branch. Investigating.

One error we identified and since fixed is a bug where the wallet you signed the nym with and the public key are different. Maybe try again with a new nym?

**Comment by DanTehrani** [comment]
@cha0sg0d 
Worked when I used a different nym! But still can't prove with the nym `nakamoto` even when I use the same address for nymSig and contentSig. So not sure what the root issue is; will keep investigating.

Another thing is that I just realized we need to let users select if they wanna use the OneNoun or ManyNouns group. Will elaborate on this in Discord!

**Review by cha0sg0d — APPROVED** [review]
Looks good and tests pass. This will be a nice addition to our nesting logic on the frontend. 

2 things I'm thinking out:
1. Remembering to run the same migration on prod @DanTehrani 
2. Knowing we have this value to query on @amirgamil @grace-fagan

**Pull request merged**
