### PR TITLE
[READY FOR REVIEW] Add basic API endpoints

### PR DESCRIPTION
**Pull request by DanTehrani**
This PR is dependent on https://github.com/personaelabs/nym/pull/16.

### CODE REVIEW

**Comment by lsankar4033** [comment]
I assume parent relationships are done by encoding the parent hash in `content` here?

**Comment by DanTehrani** [comment]
@lsankar4033 
It's done like [this](https://github.com/personaelabs/nym/blob/316583b8f40b619429edd0c1d03ba74cb834d6b0/packages/frontend/src/pages/example.tsx#L28).

So `content` is just the body of the post, and there is a separate `title`. But this is a different from the model written in [this doc](https://www.notion.so/personae-labs/Noun-Nyms-v1-data-model-structures-1b2d9e72c69c42109c74e1ed089a243b?d=a349d630af254dc6bd5b8e277ce28374#28044692669d4d999575efb40003c29c) so I do need to change the code and implement the proper model.

**Comment by cha0sg0d** [comment]
> This PR is dependent on #16.

@DanTehrani why is this PR dependent on #16? And if so, do you want to change the destination of this PR to `dan/merkletree`?

**Comment by DanTehrani** [comment]
@cha0sg0d 
This PR requires database config/migration files that are added in PR#16. So I’m not sure if targeting dan/merkle_tree’s gonna work.

And I separated the PR just to make reviewing easier!

**Comment by DanTehrani** [comment]
## This PR
- This PR isn’t using the nym circuits, and instead uses pubkey_membership.circuit from spartan-ecdsa. We can swap proving/verification to use the nym circuits once nymjs is ready.
- Implements basic APIs to create pseudo/non-pseudo posts, upvote posts, and retrieve the latest group (i.e. tree.)
- Includes [a simple example frontend ](https://github.com/personaelabs/nym/blob/dan/api/packages/frontend/src/pages/example.tsx)that interacts with the API.
- API doc in Swagger ([yml](https://github.com/personaelabs/nym/blob/dan/api/packages/frontend/public/api-doc.yml) and [viewer](https://github.com/personaelabs/nym/blob/dan/api/packages/frontend/src/pages/api-doc.tsx)).

## Example frontend using the API
https://user-images.githubusercontent.com/36762093/233021724-72bcd648-843e-4089-bdae-98a3c5ee3c5e.mov

## Important notes

User-reported timestamps
- This PR uses (signed) user-reported timestamps for timestamping
- By having a signature of a message that includes a timestamp, we can decentralize in the future without requiring others to trust our timestamps.
- User-reported timestamps are [sanity-checked in the backend](https://github.com/personaelabs/nym/blob/8d4d22b088c18b8f65f25b25565d8d20d5f04b3e/packages/frontend/src/pages/api/v1/posts.ts#L39).

Putting things together, we require users to sign the following object. We can expect other fields (e.g. tags) to be included as we develop the frontend.
```
{
	title: string,
	body: string,
	parentId?: string,
	venue: string,
	timestamp: number // UNIX timestamp
}
```

## Things left to do (Not in the scope of this PR)

- Group retrieval API optimization
  - Naively encoded member list (including each merkle proofs) is about 1MB in size for the set of owners with num-nouns = 1. We can reduce this by optimizing the merkle proofs encoding.
- Error handling
- Use nymjs
- Use EIP-712 for signing?

**Comment by DanTehrani** [comment]
@lsankar4033 
I should've mentioned that the API doc is at http://localhost:3000/api-doc. Hope it helps!

**Pull request merged**
