### PR TITLE
[WIP] Add IaC for Render (Staging env setup)

### PR DESCRIPTION
**Pull request by DanTehrani**
## This PR
Setup [Infrastructure as Code](https://render.com/docs/infrastructure-as-code) for the merkle-tree service and the database in Render.

The main motivation is to use [Preview Environments](https://render.com/docs/preview-environments), which deploys a new set of services (including the database) defined in render.yaml for every PR. With this, we can have a “staging” environment for the merkle tree service.

The existing services of prop150 [won’t be deleted](https://render.com/docs/infrastructure-as-code#no-automatic-deletions). And we probably don’t want to add their information to render.yaml since that could unexpectedly update the configuration of the services.

Once this PR is merged, we can apply render.yaml from the `Blueprints` tab in the Render dashboard.

I tested the render.yaml file in my personal account, and confirmed that it works.

## RFC
Any notable learnings re the merkle-tree/database CI/CD from prop150 that I should know?

If all looks good, pls merge! (Once merged I'll handle applying render.yaml)

### CODE REVIEW

**Comment by cha0sg0d** [comment]
@DanTehrani do you know if we can include a Github badge (like we have Vercel deployments + testing CI) that can give us a window into the success / failure of the database deployment?

**Comment by DanTehrani** [comment]
@cha0sg0d 
We'll have deployments info for Render that looks like this: (something like the ones for Vercel)

Screenshot 2023-05-08 at 22 33 57

But not sure if we can have badges in README.

**Comment by DanTehrani** [comment]
RFC on the staging env setup @cha0sg0d  @amirgamil  @lsankar4033 

Using Vercel’s cron/postgres will make CI smoother, but using beta is kinda scary…
Screenshot 2023-05-08 at 22 35 37

So I lean towards going Vercel/Render hybrid for now.

And the best CI/CD pipeline I could come up with using Vercel and Render is:

1. Open a PR
2. Vercel automatically deploys a frontend preview, and Render will alos automatically deploy a new database and the merkle-tree service scoped to the PR (we can do this using [Preview Environments](https://render.com/docs/preview-environments).
3. At this point Vercel’s preview frontend doesn’t know the URL of the database deployed in 2., so we need to copy-paste the database URL from Render to Vercel’s env var where we can specify the scope of the env var to the specific preview (as in the screenshot). 
Screenshot 2023-05-08 at 22 42 51

With this flow, we can have a database, a merkle-tree service, and the frontend **per PR. (i.e. staging env per PR)** 

Any other ideas/perspectives?

**Comment by lsankar4033** [comment]
oof, having to copy/paste env vars from db -> frontend is annoying, but using a beta service for our db in particular is really scary, esp. considering it's our source of truth for all apps

agreed that lesser of 2 evils here is to do hybrid vercel/render for now and transition when vercel postgres becomes stable

**Comment by lsankar4033** [comment]
lgtm!

**Comment by cha0sg0d** [comment]
I believe there is a way to fetch and update the `DATABASE_URL` with Github Actions.

**Pull request merged**
